from sqlalchemy import CHAR, Column, Float, ForeignKey, Index, String, Table, Text, text, Date
from sqlalchemy.dialects.mysql import INTEGER, LONGTEXT, MEDIUMINT, SMALLINT, TINYINT
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()
metadata = Base.metadata

class QuestTemplate(Base):
    __tablename__ = 'quest_template'

    entry = Column(MEDIUMINT(8), primary_key=True, server_default=text("'0'"))
    Method = Column(TINYINT(3), nullable=False, server_default=text("'2'"))
    ZoneOrSort = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    MinLevel = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    MaxLevel = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    QuestLevel = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    Type = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RequiredClasses = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RequiredRaces = Column( SMALLINT(5), nullable=False, server_default=text("'0'"))
    RequiredSkill = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RequiredSkillValue = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RequiredCondition = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RepObjectiveFaction = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RepObjectiveValue = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    RequiredMinRepFaction = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RequiredMinRepValue = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    RequiredMaxRepFaction = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RequiredMaxRepValue = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    SuggestedPlayers = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    LimitTime = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    QuestFlags = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    SpecialFlags = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    PrevQuestId = Column( MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    NextQuestId = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    ExclusiveGroup = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    NextQuestInChain = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    SrcItemId = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    SrcItemCount = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    SrcSpell = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    Title = Column(Text)
    Details = Column(Text)
    Objectives = Column(Text)
    OfferRewardText = Column(Text)
    RequestItemsText = Column(Text)
    EndText = Column( Text)
    ObjectiveText1 = Column(Text)
    ObjectiveText2 = Column(Text)
    ObjectiveText3 = Column(Text)
    ObjectiveText4 = Column(Text)
    ReqItemId1 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqItemId2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqItemId3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqItemId4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqItemCount1 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqItemCount2 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqItemCount3 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqItemCount4 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqSourceId1 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqSourceId2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqSourceId3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqSourceId4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqSourceCount1 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqSourceCount2 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqSourceCount3 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqSourceCount4 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqCreatureOrGOId1 = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    ReqCreatureOrGOId2 = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    ReqCreatureOrGOId3 = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    ReqCreatureOrGOId4 = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    ReqCreatureOrGOCount1 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqCreatureOrGOCount2 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqCreatureOrGOCount3 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqCreatureOrGOCount4 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    ReqSpellCast1 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqSpellCast2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqSpellCast3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ReqSpellCast4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewChoiceItemId1 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewChoiceItemId2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewChoiceItemId3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewChoiceItemId4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewChoiceItemId5 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewChoiceItemId6 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewChoiceItemCount1 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewChoiceItemCount2 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewChoiceItemCount3 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewChoiceItemCount4 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewChoiceItemCount5 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewChoiceItemCount6 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewItemId1 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewItemId2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewItemId3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewItemId4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewItemCount1 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewItemCount2 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewItemCount3 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewItemCount4 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    RewRepFaction1 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"), comment='faction id from Faction.dbc in this case')
    RewRepFaction2 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"), comment='faction id from Faction.dbc in this case')
    RewRepFaction3 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"), comment='faction id from Faction.dbc in this case')
    RewRepFaction4 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"), comment='faction id from Faction.dbc in this case')
    RewRepFaction5 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"), comment='faction id from Faction.dbc in this case')
    RewRepValue1 = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    RewRepValue2 = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    RewRepValue3 = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    RewRepValue4 = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    RewRepValue5 = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    RewXP = Column( MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    RewOrReqMoney = Column( INTEGER(11), nullable=False, server_default=text("'0'"))
    RewSpell = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewSpellCast = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewMailTemplateId = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    RewMailDelaySecs = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    RewMailMoney = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    PointMapId = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    PointX = Column(Float, nullable=False, server_default=text("'0'"))
    PointY = Column(Float, nullable=False, server_default=text("'0'"))
    PointOpt = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    DetailsEmote1 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    DetailsEmote2 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    DetailsEmote3 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    DetailsEmote4 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    DetailsEmoteDelay1 = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    DetailsEmoteDelay2 = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    DetailsEmoteDelay3 = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    DetailsEmoteDelay4 = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    IncompleteEmote = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    CompleteEmote = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    OfferRewardEmote1 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    OfferRewardEmote2 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    OfferRewardEmote3 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    OfferRewardEmote4 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    OfferRewardEmoteDelay1 = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    OfferRewardEmoteDelay2 = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    OfferRewardEmoteDelay3 = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    OfferRewardEmoteDelay4 = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    StartScript = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    CompleteScript = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ignored = Column(TINYINT(1), nullable=False, server_default=text("'0'"))
    parse_timestamp = Column(Date, nullable=False, server_default=text("'2004-12-12'"))

    def get_values(self, fields="__all__"):
        if fields == "__all__":
            return {k : v for k, v in self.__dict__.items() if k != "_sa_instance_state"}

        return {k : v for k, v in self.__dict__.items() if k in fields}

    @classmethod
    def get_table_name(cls):
        return cls.__tablename__

class ItemTemplate(Base):
    __tablename__ = 'item_template'

    entry = Column(MEDIUMINT(8), primary_key=True, server_default=text("'0'"))
    class_ = Column('class', TINYINT(3), nullable=False, index=True, server_default=text("'0'"))
    subclass = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    name = Column(String(255), nullable=False, server_default=text("''"))
    description = Column(String(255), nullable=False, server_default=text("''"))
    display_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    quality = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    buy_count = Column(TINYINT(3), nullable=False, server_default=text("'1'"))
    buy_price = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    sell_price = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    inventory_type = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    allowable_class = Column(MEDIUMINT(9), nullable=False, server_default=text("'-1'"))
    allowable_race = Column(MEDIUMINT(9), nullable=False, server_default=text("'-1'"))
    item_level = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    required_level = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    required_skill = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    required_skill_rank = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    required_spell = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    required_honor_rank = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    required_city_rank = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    required_reputation_faction = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    required_reputation_rank = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    max_count = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    stackable = Column(SMALLINT(5), nullable=False, server_default=text("'1'"))
    container_slots = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_type1 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value1 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    stat_type2 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value2 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    stat_type3 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value3 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    stat_type4 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value4 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    stat_type5 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value5 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    stat_type6 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value6 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    stat_type7 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value7 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    stat_type8 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value8 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    stat_type9 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value9 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    stat_type10 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    stat_value10 = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    delay = Column(SMALLINT(5), nullable=False, server_default=text("'1000'"))
    range_mod = Column(Float, nullable=False, server_default=text("'0'"))
    ammo_type = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    dmg_min1 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_max1 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_type1 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    dmg_min2 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_max2 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_type2 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    dmg_min3 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_max3 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_type3 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    dmg_min4 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_max4 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_type4 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    dmg_min5 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_max5 = Column(Float, nullable=False, server_default=text("'0'"))
    dmg_type5 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    block = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    armor = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    holy_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    fire_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    nature_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    frost_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    shadow_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    arcane_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    spellid_1 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spelltrigger_1 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    spellcharges_1 = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    spellppmrate_1 = Column(Float, nullable=False, server_default=text("'0'"))
    spellcooldown_1 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    spellcategory_1 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    spellcategorycooldown_1 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    spellid_2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spelltrigger_2 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    spellcharges_2 = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    spellppmrate_2 = Column(Float, nullable=False, server_default=text("'0'"))
    spellcooldown_2 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    spellcategory_2 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    spellcategorycooldown_2 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    spellid_3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spelltrigger_3 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    spellcharges_3 = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    spellppmrate_3 = Column(Float, nullable=False, server_default=text("'0'"))
    spellcooldown_3 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    spellcategory_3 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    spellcategorycooldown_3 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    spellid_4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spelltrigger_4 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    spellcharges_4 = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    spellppmrate_4 = Column(Float, nullable=False, server_default=text("'0'"))
    spellcooldown_4 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    spellcategory_4 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    spellcategorycooldown_4 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    spellid_5 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spelltrigger_5 = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    spellcharges_5 = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    spellppmrate_5 = Column(Float, nullable=False, server_default=text("'0'"))
    spellcooldown_5 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    spellcategory_5 = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    spellcategorycooldown_5 = Column(INTEGER(11), nullable=False, server_default=text("'-1'"))
    bonding = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    page_text = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    page_language = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    page_material = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    start_quest = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    lock_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    material = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    sheath = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    random_property = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    set_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    max_durability = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    area_bound = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    map_bound = Column(SMALLINT(6), nullable=False, server_default=text("'0'"))
    duration = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    bag_family = Column(MEDIUMINT(9), nullable=False, server_default=text("'0'"))
    disenchant_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    food_type = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    min_money_loot = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    max_money_loot = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    extra_flags = Column(TINYINT(1), nullable=False, server_default=text("'0'"))
    ignored = Column(TINYINT(1), nullable=False, server_default=text("'0'"))

    @classmethod
    def get_table_name(cls):
        return cls.__tablename__


class CreatureTemplate(Base):
    __tablename__ = 'creature_template'

    entry = Column(MEDIUMINT(8), primary_key=True, server_default=text("'0'"))
    display_id1 = Column(MEDIUMINT(8), nullable=False, index=True, server_default=text("'0'"))
    display_id2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    display_id3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    display_id4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    mount_display_id = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    name = Column(CHAR(100), nullable=False, index=True, server_default=text("'0'"))
    subname = Column(CHAR(100))
    static_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    gossip_menu_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    level_min = Column(TINYINT(3), nullable=False, server_default=text("'1'"))
    level_max = Column(TINYINT(3), nullable=False, server_default=text("'1'"))
    faction = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    npc_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    speed_walk = Column(Float, nullable=False, server_default=text("'1'"), comment='Result of 2.5/2.5, most common value')
    speed_run = Column(Float, nullable=False, server_default=text("'1.14286'"), comment='Result of 8.0/7.0, most common value')
    scale = Column(Float, nullable=False, server_default=text("'1'"))
    detection_range = Column(Float, nullable=False, server_default=text("'20'"))
    call_for_help_range = Column(Float, nullable=False, server_default=text("'5'"))
    leash_range = Column(Float, nullable=False, server_default=text("'0'"))
    rank = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    xp_multiplier = Column(Float, nullable=False, server_default=text("'1'"))
    damage_multiplier = Column(Float, nullable=False, server_default=text("'1'"))
    armor_multiplier = Column(Float, nullable=False, server_default=text("'1'"))
    health_multiplier = Column(Float, nullable=False, server_default=text("'1'"))
    mana_multiplier = Column(Float, nullable=False, server_default=text("'1'"))
    damage_variance = Column(Float, nullable=False, server_default=text("'0.14'"))
    damage_school = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    base_attack_time = Column(INTEGER(10), nullable=False, server_default=text("'2000'"))
    ranged_attack_time = Column(INTEGER(10), nullable=False, server_default=text("'2000'"))
    unit_class = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    unit_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    dynamic_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    beast_family = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    trainer_type = Column(TINYINT(4), nullable=False, server_default=text("'0'"))
    trainer_spell = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    trainer_class = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    trainer_race = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    type = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    type_flags = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    loot_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    pickpocket_loot_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    skinning_loot_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    holy_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    fire_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    nature_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    frost_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    shadow_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    arcane_res = Column(SMALLINT(5), nullable=False, server_default=text("'0'"))
    spell_id1 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spell_id2 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spell_id3 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spell_id4 = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    spell_list_id = Column(INTEGER(11), nullable=False, server_default=text("'0'"))
    pet_spell_list_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    auras = Column(Text)
    gold_min = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    gold_max = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    ai_name = Column(CHAR(64), nullable=False, server_default=text("''"))
    movement_type = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    inhabit_type = Column(TINYINT(3), nullable=False, server_default=text("'3'"))
    civilian = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    racial_leader = Column(TINYINT(3), nullable=False, server_default=text("'0'"))
    regeneration = Column(TINYINT(3), nullable=False, server_default=text("'3'"))
    equipment_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    trainer_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    vendor_id = Column(MEDIUMINT(8), nullable=False, server_default=text("'0'"))
    mechanic_immune_mask = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    school_immune_mask = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    flags_extra = Column(INTEGER(10), nullable=False, server_default=text("'0'"))
    script_name = Column(CHAR(64), nullable=False, server_default=text("''"))

    @classmethod
    def get_table_name(cls):
        return cls.__tablename__
